Upgrade jsdom canvas
SyslogicNL/pdf-extractor pull request #14
Opened 2018-11-05 08:25 UTC by lightpriest

Upgrades jsdom and canvas to the latest packages. This should make pdf-extractor easier to install since canvas >= 2 comes with pre-built binaries automatically.

Made the proper adjustments to domfacade to deal with the changes made to jsdom and canvas.

2018-11-06 12:25 UTC, Hikariii requested changes
Thank you for your contribution.
There is still one change missing with the new canvas that is giving a new error:
Warning: Native JPEG decoding failed -- trying to recover: Image is not a constructor
If you can fix that i'll merge the change.

2018-11-06 12:25 UTC, Hikariii commented on lib/pdfjs-utils/domfacade.js
> +const { Canvas, Context2d } = require("jsdom/lib/jsdom/utils").Canvas;
Canvas 2 also export `Image` and `ImageData` in a new way.
This is exported here https://github.com/ScientaNL/pdf-extractor/blob/master/lib/pdfjs-utils/domfacade.js#L199-L200

```suggestion
const { Canvas, Context2d, Image, ImageData } = require("jsdom/lib/jsdom/utils").Canvas;
```

2018-11-06 12:25 UTC, Hikariii commented on lib/pdfjs-utils/domfacade.js
> +const { Canvas, Context2d } = require("jsdom/lib/jsdom/utils").Canvas;
Can you change lines 199 and 200 too with after importing them from canvas:
```
exports.Image = Image;
exports.ImageData = ImageData;
```

2018-11-07 07:44 UTC, lightpriest commented on lib/pdfjs-utils/domfacade.js
> +const { Canvas, Context2d } = require("jsdom/lib/jsdom/utils").Canvas;
Oops, missed that. Ran the examples on the README to make sure.

2018-11-07 07:46 UTC, Hikariii commented
Thank you very much!

2018-11-07 07:46 UTC, merged